name: deploy_sgzs_web_front

on:
  push:
    branches:
      - sgzs

jobs:
  dev-front-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node.js
        uses: actions/checkout@v4
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: clean Server Old Files
        uses: fifsky/ssh-action@master
        with:
          command: rm -rf /root/lesson/lesson_web_front/assets/*
          host: ${{ secrets.HW_TEST_SERVER }}
          user: ${{ secrets.HW_SERVER_USERNAME }}
          pass: ${{ secrets.HW_SERVER_PWD }}
          args: "-tt"

      - name: Scp dist To HW Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HW_TEST_SERVER }}
          username: ${{ secrets.HW_SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ github.workspace }}/dist/*
          target: /root/lesson/lesson_web_front
          strip_components: 3